[package]
name = "bevy_sprite3d"
version = "2.7.0"
edition = "2021"

description = "Bevy Plugin to allow using 2d sprites in a 3d scene."
license = "MIT"
readme = "readme.md"
repository = "https://github.com/FraserLee/bevy_sprite3d"
keywords = ["gamedev", "bevy", "sprite", "3d"]

[dependencies.bevy]
# Switch back to "1.13" once that version comes out.
# I don't know if there's a better way to do this.
# version = "0.12"
git = "https://github.com/bevyengine/bevy.git"
default-features = false
features = ["bevy_asset", "bevy_pbr", "bevy_sprite"]

[dev-dependencies]
# bevy.version = "0.12" # (include default features when running examples)
bevy = { git = "https://github.com/bevyengine/bevy.git" }
rand = "0.8"
